### ISSUE TITLE
SendCode

### ISSUE THREAD

**Issue by mahdizojaji** [DjangoQA/DjangoQA-DRF#1]
**SubTasks:**
- [ ] API for sending numerical code to specific email
- [ ] Send code flow for email in telegram bot

**Review:**
- [ ] pull remote
- [ ] Write Code
- [ ] Write Test
- [ ] Write postman requests
- [ ] Write swagger doc
- [ ] Add new package to requirements
- [ ] pull remote
- [ ] Check migrations again & run project for test
- [ ] Make pull request

**Comment by mahdizojaji** [comment]
@MrMohammadY 
This task was changed.
Please read new changes & Do the new stuff.

**Comment by mahdizojaji** [comment]
# Hint

### API Input:
* phone_number

### API Response:
* success
* new_user
* expire time
* More needed fields

### SMS Provider
* Use [Ghasedak](https://ghasedak.me/docs) provider.
