### ISSUE TITLE
Delete Question

### ISSUE THREAD

**Issue by mahdizojaji** [DjangoQA/DjangoQA-DRF#11]
**Dependency:**
CreateQuestion ( #8 )

**SubTasks:**
- [ ] API for retrieve  a question.

**Review:**
- [ ] Write Code
- [ ] Write Test
- [ ] Write postman requests
- [ ] Write swagger doc
- [ ] Make pull request
