### ISSUE TITLE
RetrieveAnswer

### ISSUE THREAD

**Issue by mahdizojaji** [DjangoQA/DjangoQA-DRF#17]
**Dependency:**
CreateAnswer ( #15 )

**SubTasks:**
- [ ] API for get specific answer of question

**Review:**
- [ ] Write Code
- [ ] Write Test
- [ ] Write postman requests
- [ ] Write swagger doc
- [ ] Make pull request
