### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Speedssster** [DjangoQA/DjangoQA-DRF#2]
**SubTasks:**
- [ ] API for validate code value & expire date for specific email
- [ ] Validate code flow for email in telegram bot

**Review:**
- [ ] Write Code
- [ ] Write Test
- [ ] Write postman requests
- [ ] Write swagger doc
- [ ] Make pull request
