### ISSUE TITLE
RetrieveMyInfo

### ISSUE THREAD

**Issue by mahdizojaji** [DjangoQA/DjangoQA-DRF#5]
**SubTasks:**
- [ ] Show profile flow in telegram bot
- [ ] API for get own data

**Review:**
- [ ] Write Code
- [ ] Write Test
- [ ] Write postman requests
- [ ] Write swagger doc
- [ ] Make pull request
