### ISSUE TITLE
UpdateMyInfo

### ISSUE THREAD

**Issue by mahdizojaji** [DjangoQA/DjangoQA-DRF#6]
**SubTasks:**
- [ ] API for update/partialupdate own data

**Review:**
- [ ] Write Code
- [ ] Write Test
- [ ] Write postman requests
- [ ] Write swagger doc
- [ ] Make pull request
