### ISSUE TITLE
TopUsers

### ISSUE THREAD

**Issue by mahdizojaji** [DjangoQA/DjangoQA-DRF#7]
**SubTasks:**
- [ ] API for get top users (top scores)

**Review:**
- [ ] Write Code
- [ ] Write Test
- [ ] Write postman requests
- [ ] Write swagger doc
- [ ] Make pull request
