### ISSUE TITLE
CreateQuestion

### ISSUE THREAD

**Issue by mahdizojaji** [DjangoQA/DjangoQA-DRF#8]
**SubTasks:**
- [ ] API for create qustion

**Review:**
- [ ] Write Code
- [ ] Write Test
- [ ] Write postman requests
- [ ] Write swagger doc
- [ ] Make pull request
